


### sample [get, /name]

    + Attributes
        + name1 (optional, number) - descr1
        + name2 (required, object)

    + Request request1 (application/json)
    + Response 200 (application/json)
    
    + Request (application/json)
    + Response 200 (application/json)
        + Headers
            key1: value1

    
### lololol [get, /name]

    + Parameters
        + name1 (optional, bool) - descr1
        + name2 (required, string) - descr2
    + Request request1 (application/json)
        + Headers
            key1: value1
        + Body
            {
                value: {
                    json: type
                }
            }
        + Schema
            SCHEMA

    + Response 200 (application/json)
        + Headers
            key1: value1
        + Body
            BODY
    
    + Request (application/json)
        + Headers
            key1: value1
        + Body
            BODY
    + Response 200 (application/json)

##