
FORMAT: 1A
NAME: GoLamaGo
HOST: http://lama.apiary.io/

# Users

Api for users

# Group Users

## User Resource [/user]

### Get User [GET, /user]
    + Options
        + Iterative
    + Request
    + Response 200 (Application/json)

### Create User [POST, /users]

+ Request (application/json)
+ Response 200 (application/json)

### Connection [POST, /connect/token]

    + Attributes
        + client_id (required, string)
        + refresh_token (optional, string)
        + grant_type (required, string)
        + code (optional, string)
    + Parameters
        + client_id (required, string)
        + refresh_token (optional, string)
        + grant_type (required, string)
        + code (optional, string)

    + Request
    + Response 200 (Application/json)

### Update User [POST, /user]

    + Request (application/json)
    + Response 204 (application/json)

### Add Address [POST, /user/profile/address]

    + Request (application/json)
    + Response 201 (application/json) 

### Update Address [PUT, /user/profile/address/{address_id}]

    + Attributes
        + address_id (required, string)
    + Parameters
        + address_id (required, string)

+ Request (application/json)
+ Response 204 (application/json) 

### Remove Address [DELETE, /user/profile/address/{address_id}]
    + Attributes
        + address_id (required, string)
    + Parameters
        + address_id (required, string)
        
    + Request (application/json)
    + Response 204 (application/json)

### Get Profile [GET, /user/profile]
    + Options
        + Iterative
    + Request
    + Response 200 (Application/json)

# Group Shops

## Shops [/shops]

### Shop Gorups [GET, /shopgroups]

+ Request (application/json)
+ Response 200 (application/json)

### Shops [GET, /shops]
    
    + Attributes
        + location (optional, string)
        + group (optional, string)
        + type (required, string)
    + Parameters
        + location (optional, string)
        + group (optional, string)
        + type (required, string)
    
    + Request (application/json)
    + Response 204(application/json)

# Group Orders

## Orders [/orders]

### Order list [GET, /orders]
    + Attributes
        + skip (optional, long)
        + n (optional, long)

    + Parameters
        + skip (optional, long)
        + n (optional, long)

    + Request (application/json)
    + Response 200 (application/json)
        
### Create Order [POST, /orders]

+ Options
    + Iterative

+ Request (application/json)
+ Response 201 (application/json)
    
### Get Order Info [GET, /orders/{id}]
    + Options
        + Iterative

    + Request (application/json)
    + Response 200 (application/json)
    
### Short Order Status [GET, /orders/{id}/status]

    + Attributes
        + id (required, string)
    + Parameters
        + id (required, string)
    + Request (application/json)
    + Response 200 (application/json)
    
### Swap Items [POST, /orders/{id}/items/{itemId}]
    + Attributes
        + id (required, string)
    + Parameters
        + id (required, string)
    + Request (application/json)
    + Response 200 (application/json)

### Remove Unawailable Items [DELETE, /orders/{id}/items/{itemId}]
    + Options
        + Iterative
    + Request
    + Response 200 (application/json)

### Denial Of Items [POST, /orders/{id}/deny]
    + Options
        + Iterative
    + Request
    + Response 200 (application/json)

### Confirm Order Completion [POST, /orders/{id}/confirmation]
    + Options
        + Iterative
    + Request
    + Response 204 (application/json)

# Group Carts

## Card Resources [/cart]

### Get Content [GET, /cart/{shopId}]
    + Options
        + Iterative
    + Request
    + Response 200 (application/json)
        
### Set Address [POST, /cart/{shopId}/delivery]
    + Options
        + Iterative
    + Request
    + Response 204 (application/json)

### Get Available Delivery Intervals [GET, /cart/{shopId}/delivery/times]
    + Options 
        + Iterative
    + Request
    + Response 200 (application/json)

### Add Item [POST, /cart/{shopId}/items]
    + Options
        + Iterative
    + Request
    + Response 200 (Application/json)
        
### Clear Cart For Shop [DELETE, /cart/{shopId}]
    + Options
        + Iterative
    + Request
    + Response 204 (Application/json)

### Modify Item [PUT,/cart/{shopId}/items/{itemId}]
    + Options 
        + Iterative
    + Request 
    + Response 200 (Application/json)
        
### Remove Item [DELETE, /cart/{shopId}/items/{itemId}]
    + Options
        + Iterative
    + Request
    + Response 200 (Application/json)
