
FORMAT: 1A
NAME: GoLamaGo
HOST: http://lama.apiary.io/

# Users

Api for users

# Group Users

## User Resource [/user]

### Create User [POST, /users]

+ Request (application/json)
    + Body
        {
            "phone": "+79192444804"
        }
+ Response 200 (application/json)
    + Body
        {
            "key": "secretKey"
        }
+ Request (application/json)
    + Body
        {
            "phone": "+79103468893"
        }
+ Response 400 (application/json)
    + Body
        {
            error: "Bad phone"
        }
+ Request (application/json)
+ Response 400 (application/json)
    + Body
        {
            error: "Bad request"
        }
### Connection [POST, /connect/token]

    + Attributes
        + client_id (required, string)
        + refresh_token (optional, string)
        + grant_type (required, string)
        + code (optional, string)
    + Parameters
        + client_id (required, string)
        + refresh_token (optional, string)
        + grant_type (required, string)
        + code (optional, string)

    + Request
        + Parameters
            client_id: "lama.client.ios"
            grant_type: "authorization_code"
            code: "secretKey:0000"
    + Response 200 (Application/json)
        + Body
            {
                "access_token": "access_token",
                "refresh_token": "refresh_token"
            }
    + Request
        + Parameters
            client_id: "lama.client.android"
            grant_type: "authorization_code"
            code: "secretKey:0000"
    + Response 200 (Application/json)
        + Body
            {
                "access_token": "access_token",
                "refresh_token": "refresh_token"
            }
    + Request
        + Parameters
            client_id: "lama.client.ios"
            grant_type: "authorization_code"
            code: "secretKey:1111"
    + Response 200 (Application/json)
        + Body
            {
                error: "bad code"
            }
    + Request
        + Parameters
            client_id: "lama.client.android"
            grant_type: "authorization_code"
            code: "secretKey:1111"
    + Response 200 (Application/json)
        + Body
            {
                error: "bad code"
            }

    + Request
        + Parameters
            client_id: "lama.client.ios"
            grant_type: "refresh_token"
            refresh_token: "refresh_token"
    + Response 200 (Application/json)
        + Body
            {
                "access_token": "access_token",
                "refresh_token": "refresh_token"
            }


### Update User [POST, /user]
    + Request (application/json)
        + Body 
            {
                "firstName": "0",
                "lastName": "0",
                "email": "0",
                "phone": "0"
            }
    + Response 204 (application/json)

### Add Address [POST, /user/profile/address]

+ Request (application/json)
    + Body
        {
            "address": "1",
            "entrance": "1",
            "floor": "1",
            "apartment": "1",
            "doorPhone": "1",
            "recipientFirstName": "1",
            "recipientLastName": "1",
            "recipientPhone": "1",
            "location": {
                "latitude": 1,
                "longitude": 1
            },
            "note": "не кричите громко"
        }
+ Response 201 (application/json) 
    + Body
        {
            "id": "1",
        }
+ Request (application/json)
+ Response 400 (application/json)
    + Body
        {"error" : "bad request"}

### Update Address [PUT, /user/profile/address/{address_id}]

    + Attributes
        + address_id (required, string)
    + Parameters
        + address_id (required, string)

+ Request (application/json)

    + Parameters
        address_id: "1"

    + Body
        {
            "id": "1",
            "address": "1",
            "entrance": "1",
            "floor": "1",
            "apartment": "1",
            "doorPhone": "1",
            "recipientFirstName": "1",
            "recipientLastName": "1",
            "recipientPhone": "1",
            "location": {
                "latitude": 1,
                "longitude": 1
            },
            "note": "не кричите громко"
        }
+ Response 204 (application/json) 

### Remove Address [DELETE, /user/profile/address/{address_id}]
    + Attributes
        + address_id (required, string)
    + Parameters
        + address_id (required, string)
        
    + Request (application/json)
        + Parameters
            address_id: "1"
    + Response 204 (application/json)

### Get Profile [GET, /user/profile]
    + Request
    + Response 200 (Application/json)
        + Body
            {
    "id": "XXYYZZ",
    "firstName": "Виточка",
    "lastName": "Программист",
    "email": "email@user.com",
    "phone": "+79992223344",
    "birthDate": "2017-09-16T12:38:21+0000",
    "addresses": [
        {
            "id": "ZXCC",                
            "address" : "Южнобутовская ул. вл66",
            "entrance" : "",
            "floor": "",
            "apartment": "келья дьякона Данунахова",
            "doorPhone": "1488",
            "recipientFirstName" : "Иннокентий",
            "recipientLastName" : "Данунахов",
            "recipientPhone" : "55503523355",
            "latitude" : 37.526525,
            "longitude": 55.535164,
            "note": "не кричите громко",
            "isMain": false
        }
    ],
    "cards": [
        {
            "id": "card094234dgf",
            "pan": "411111******1111"
        },
        {
            "id": "card0942334dgf",
            "pan": "311111******1111"
        }
    ]
}

 + Request
    + Response 200 (Application/json)
        + Body
            {
    "id": "XXYYZZ",
    "firstName": "FirstName",
    "lastName": "LastName",
    "email": "email@user.com",
    "phone": "+79992223344",
    "birthDate": "2017-07-18T08:56:35Z",
    "addresses": [
        {
            "id": "ZXCC",                
            "address" : "Южнобутовская ул. вл66",
            "entrance" : "",
            "floor": "",
            "apartment": "келья дьякона Данунахова",
            "doorPhone": "1488",
            "recipientFirstName" : "Иннокентий",
            "recipientLastName" : "Данунахов",
            "recipientPhone" : "55503523355",
            "latitude" : 37.526525,
            "longitude": 55.535164,
            "note": "не кричите громко",
            "isMain": false
        }
    ],
    "cards": [
        {
            "id": "card094234dgf",
            "pan": "411111******1111"
        }
    ]
}

# Group Shops

## Shops [/shops]

### Shop Tags [GET, /shoptags]

+ Request
+ Response 200 (application/json)

    + Body
        [
            {
                "name": "Товары для животных",
                "tag": "0"
            },
            {
                "name": "Продукты питания",
                "tag": "1"
            },
            {
                "name": "Вкусняхи",
                "tag": "2"
            },
            {
                "name": "Бытовые товары",
                "tag": "3"
            },
            {
                "name": "Товары для детей",
                "tag": "4"
            }
        ]

### Shop Gorups [GET, /shopgroups]

+ Request (application/json)
+ Response 200 (application/json)
    + Body
        [
            {
                "id": "0",
                "name": "Metro"
            },
            {
                "id": "1",
                "name": "Лента"
            },
            {
                "id": "2",
                "name": "Billa"
            },
            {
                "id": "3",
                "name": "Перекресток"
            },
            {
                "id": "4",
                "name": "Ашан"
            },
            {
                "id": "5",
                "name": "АвтоСеть"
            }
        ]

### Shops [GET, /shops]
    
    + Attributes
        + location (optional, string)
        + group (optional, string)
        + type (required, string)
    + Parameters
        + location (optional, string)
        + group (optional, string)
        + type (required, string)
    
    + Request (application/json)
        + Parameters
            location: "55.0,55.0"
            type: selfpickup
    + Response 200 (application/json)
       + Body
         [
        {
            "id": "0",
            "groupId": "5",
            "name": "Свежая выпечка и кондитерские изделия",
            "address": "0",
            "distance": 200,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/AoPs2il36jk2guk/avtoset_logo.png",
            "pinIcon": "0",
            "price": 10,
            "eta": 60,
            "tags": ["2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "1",
            "groupId": "2",
            "name": "Продукты питания и хоз товары",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/ExjqC9QCaesoAN4/billa_logo.png",
            "pinIcon": "0",
            "price": 10,
            "eta": 220,
            "tags": ["1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "2",
            "groupId": "1",
            "name": "Товары для животных",
            "address": "0",
            "distance": 400,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/RKEjv2TPHpBkJxL/lenta_logo.png",
            "pinIcon": "0",
            "price": 120,
            "eta": 60,
            "tags": ["0"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Гипермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/dkpAJM6lcf5d8h7/metro_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2", "3", "4"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Супермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/50VjYRhtARzYTNT/perekrestok_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Гипермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/1FSP7phC6mtuKP6/ashan_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        }
    ]
    + Request (application/json)
        + Parameters
            location: "55.0,55.0"
            type: delivery
    + Response 200 (application/json)
        + Body
         [
        {
            "id": "0",
            "groupId": "5",
            "name": "Свежая выпечка и кондитерские изделия",
            "address": "0",
            "distance": 200,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/AoPs2il36jk2guk/avtoset_logo.png",
            "pinIcon": "0",
            "price": 10,
            "eta": 60,
            "tags": ["2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "1",
            "groupId": "2",
            "name": "Продукты питания и хоз товары",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/ExjqC9QCaesoAN4/billa_logo.png",
            "pinIcon": "0",
            "price": 10,
            "eta": 220,
            "tags": ["1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "2",
            "groupId": "1",
            "name": "Товары для животных",
            "address": "0",
            "distance": 400,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/RKEjv2TPHpBkJxL/lenta_logo.png",
            "pinIcon": "0",
            "price": 120,
            "eta": 60,
            "tags": ["0"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Гипермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/dkpAJM6lcf5d8h7/metro_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2", "3", "4"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Супермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/50VjYRhtARzYTNT/perekrestok_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        },
        {
            "id": "3",
            "groupId": "2",
            "name": "Гипермаркет",
            "address": "0",
            "distance": 300,
            "photo": "https://s3.amazonaws.com/uploads.hipchat.com/18933/4501153/1FSP7phC6mtuKP6/ashan_logo.png",
            "pinIcon": "0",
            "price": 1,
            "eta": 5,
            "tags": ["0","1", "2"],
            "location": {
                "latitude": 0,
                "longitude": 0
            }
        }
    ]

# Group Orders

## Orders [/orders]

### Order list [GET, /orders]
    + Attributes
        + skip (optional, long)
        + n (optional, long)

    + Parameters
        + skip (optional, long)
        + n (optional, long)

    + Request (application/json)
        + Parameters
            skip: 10
            n: 10
    + Response 200 (application/json)
        + Body
                {
                    "n": 10,
                    "skip": 10,
                    "count": 2,
                    "orders": [
                        {
                            "id": "ZZXX",
                            "qty": 5,
                            "total": 1500,
                            "date": "",
                            "status": "active",
                            "address": "Южнобутовская ул. вл66",
                            "shop": {
                                "id": "shopIdXXD",
                                "groupId": "groupId",
                                "photo": "sdfsdf"
                            }
                        },
                        {
                            "id": "ZZXX",
                            "qty": 5,
                            "total": 1500,
                            "date": "",
                            "status": "completed",
                            "address": "Южнобутовская ул. вл66",
                             "shop": {
                                "id": "shopIdXXD",
                                "groupId": "groupId",
                                "photo": "sdfsdf"
                            }
                        }
                    ]
                }

### Create Order [POST, /orders]

+ Options
    + Iterative

+ Request (application/json)
+ Response 200 (application/json)
    + Body
{
    "shopId" : "shopIdXXZZ",
    "items" : [
        {
            "itemId": "XXYYWW",
            "qty": 2,
        }
    ],
    "address" : {
        "address" : "Южнобутовская ул. вл66",
        "entrance" : "",
        "floor": "",
        "apartment": "келья дьякона Данунахова",
        "doorPhone": "1488",
        "recipientFirstName" : "Иннокентий",
        "recipientLastName" : "Данунахов",
        "recipientPhone" : "55503523355",
        "latitude" : 37.526525,
        "longitude": 55.535164,
        "note": "не кричите громко"
    },
    "dueTime" : "",
}

+ Request (application/json)
+ Response 200 (application/json)
    + Body
{
    "shopId" : "123",
    "items" : [
        {
            "itemId": "XXYYWW",
            "qty": 2
        }
    ],
    "address" : {
        "address" : "Южнобутовская ул. вл66",
        "entrance" : "",
        "floor": "",
        "apartment": "келья дьякона Данунахова",
        "doorPhone": "1488",
        "recipientFirstName" : "Иннокентий",
        "recipientLastName" : "Данунахов",
        "recipientPhone" : "55503523355",
        "latitude" : 37.526525,
        "longitude": 55.535164,
        "note": "не кричите громко"
    },
    "dueTime" : ""
}

+ Request (application/json)
+ Response 200 (application/json)
    + Body
{
    "shopId" : "098",
    "items" : [
        {
            "itemId": "XXYYWW",
            "qty": 2
        }
    ],
    "address" : {
        "address" : "Южнобутовская ул. вл66",
        "entrance" : "",
        "floor": "",
        "apartment": "келья дьякона Данунахова",
        "doorPhone": "1488",
        "recipientFirstName" : "Иннокентий",
        "recipientLastName" : "Данунахов",
        "recipientPhone" : "55503523355",
        "latitude" : 37.526525,
        "longitude": 55.535164,
        "note": "не кричите громко"
    },
    "dueTime" : ""
}

+ Request (application/json)
+ Response 200 (application/json)
    + Body
{
    "shopId" : "lllllllll",
    "items" : [
        {
            "itemId": "XXYYWW",
            "qty": 2
        }
    ],
    "address" : {
        "address" : "Южнобутовская ул. вл66",
        "entrance" : "",
        "floor": "",
        "apartment": "келья дьякона Данунахова",
        "doorPhone": "1488",
        "recipientFirstName" : "Иннокентий",
        "recipientLastName" : "Данунахов",
        "recipientPhone" : "55503523355",
        "latitude" : 37.526525,
        "longitude": 55.535164,
        "note": "не кричите громко"
    },
    "dueTime" : ""
}

### Get Order Info [GET, /orders]
    + Attributes
        + id (required, string)
    + Parameters
        + id (required, string)

    + Request (application/json)
        + Parameters
            id: "aaa"

    + Response 200 (application/json)
        + Body
            {
        "id": "orderXZZVV",
        "shopId" : "shopIdSDSD",
        "items": [
            {
                "id": "XXYYZZ",
                "name": "Водка \"Путинка\"",
                "qty": 2,
                "price": 75.0,
                "total": 150.0,
                "added": "2017-08-09T09:45:15Z+03:00",
                "status": {
                    "id": "confirmWeightRequest",
                    "qty": 1,
                    "weight": 2.530
                }
            },
            {
                "id": "XXYYWW",
                "name": "Килька в томатном соусе 200г",
                "qty": 1,
                "price": 60.0,
                "total": 60.0,
                "added": "2017-08-09T09:45:15Z+03:00",
                "status": {
                    "id": "packed"
                }
            }                
        ],
        "address" : {
            "address" : "Южнобутовская ул. вл66",
            "entrance" : "",
            "floor": "",
            "apartment": "келья дьякона Данунахова",
            "doorPhone": "1488",
            "recipientFirstName" : "Иннокентий",
            "recipientLastName" : "Данунахов",
            "recipientPhone" : "55503523355",
            "latitude" : 37.526525,
            "longitude": 55.535164,
            "note": "не кричите громко"
        },
        "dueTime" : "",
        "price": {
            "items": 210,
            "delivery": 200,
            "discount": 10,
            "total": 400
        },
        "status": "InProgress",
        "tasks" : [
            {
                "taskId": "azsxdcfv",
                "type": "pack",
                "status": "RequiresAproval",
                "assignee": null
            },
            {
                "taskId": "azsxdcfv",
                "type": "deliver",
                "status": "New",
                "assignee": {
                    "id": "userIDZXX",
                    "firstName": "Курьер",
                    "lastName": "Курьеров",
                    "photo": "",
                    "phone": 495654795,
                    "latitude" : 37.526525,
                    "longitude": 55.535164
                }
            }
        ]
    }

### Short Order Status [GET, /orders/{id}/status]

+ Attributes
    + id (required, string)
+ Parameters
    + id (required, string)
+ Request (application/json)
    + Parameters
        id: "ololol"
+ Response 200 (application/json)
    + Body
        {
  "status": "new",
  "tasks": [
    {
      "type": "pack",
      "status": "RequiresAproval"
    },
    {
      "type": "deliver",
      "status": "New",
      "latitude": 37.526525,
      "longitude": 55.535164
    }
  ]
}

### Change Order Status [POST, /orders/{id}/status]

    + Attributes
        + id (required, string)
    + Parameters
        + id (required, string)
    + Request (application/json)
        + Parameters
            id: "ololol"
        + Body 
            {
  "status": "InProgress",
  "rating": {
    "value": 1,
    "comment": "да норм, чо"
  }
}
+ Response 204 (application/json)

### Swap Items [POST, /orders/{id}/swap]
+ Attributes
    + id (required, string)
+ Parameters
    + id (required, string)
+ Request (application/json)
    + Parameters
        id: "ololol"
    + Body 
        {
    "oldItem" : {
        "id": "XXYYWW",
        "qty": 2
    },
    "newItem" : {
        "id": "ZZZWWW",
        "qty": 1
    }
}
+ Response 204 (application/json)

# Group Carts

## Card Resources [/cart]

### Get Contents [GET, /cart]
+ Options
    + Iterative
+ Request (application/json)
+ Response 200 (application/json)
    + Body
        [
    {
        "count": 3,
        "shop": {
            "id": "shopZYX",
            "groupId": "metro",
            "name": "",
            "address": "проспект Мира, 211к1",
            "photo": ""
        },
        "delivery" : {
            "address" : "Южнобутовская ул. вл66",
            "entrance" : "",
            "floor": "",
            "apartment": "келья дьякона Данунахова",
            "doorPhone": "1488",
            "recipientFirstName" : "Иннокентий",
            "recipientLastName" : "Данунахов",
            "recipientPhone" : "55503523355",
            "latitude" : 37.526525,
            "longitude": 55.535164,
            "note": "не кричите громко"
        },
        "items": [
            {
                "id": "XXYYZZ",
                "name": "Водка \"Путинка\"",
                "qty": 2,
                "price": 75.0,
                "total": 150.0,
                "added": "2017-08-09T09:45:15Z+03:00",
                "avail": true
            },
            {
                "id": "XXYYWW",
                "name": "Килька в томатном соусе 200г",
                "qty": 1,
                "price": 60.0,
                "total": 60.0,
                "added": "2017-08-09T09:45:15Z+03:00",
                "avail": false
            },
            {
                "id": "XXYYWW",
                "name": "Помидор красивый",
                "qty": 1,
                "price": 60.0,
                "total": 30.0,
                "weight": 0.500,
                "added": "2017-08-09T09:45:15Z+03:00",
                "avail": false
            }
        ],
        "price": {
            "items": 210,
            "delivery": 200,
            "discount": 10,
            "total": 400
        }
    },
    {
        "count": 1,
        "shop": {
            "id": "shopYXZ",
            "groupId": "lenta",
            "name": "",
            "address": "1я Останкинская улица, 55",
            "photo": ""
        },
        "items": [
            {
                "id": "XXYYZZ",
                "name": "Водка \"Тракториста\"",
                "qty": 1,
                "price": 300.0,
                "total": 300.0,
                "added": "2017-08-09T09:45:15Z+03:00",
                "avail": true
            }
        ],
        "price": {
            "items": 210,
            "delivery": 200,
            "discount": 10,
            "total": 400
        }
    }
]

### Get Content [GET, /cart/{shopId}]
    + Attributes
        + shopId (required, string)
    + Parameters
        + shopId (required, string)
    + Request (application/json)
        + Parameters
            shopId: "ololol"
    + Response 200 (application/json)
        + Body

{
    "count": 3,
    "shop": {
        "id": "shopZYX",
        "groupId": "metro",
        "name": "",
        "address": "проспект Мира, 211к1",
        "photo": ""
    },
    "delivery" : {
        "address" : "Южнобутовская ул. вл66",
        "entrance" : "",
        "floor": "",
        "apartment": "келья дьякона Данунахова",
        "doorPhone": "1488",
        "recipientFirstName" : "Иннокентий",
        "recipientLastName" : "Данунахов",
        "recipientPhone" : "55503523355",
        "latitude" : 37.526525,
        "longitude": 55.535164,
        "note": "не кричите громко"
    },
    "items": [
        {
            "id": "XXYYZZ",
            "name": "Водка \"Путинка\"",
            "qty": 2,
            "price": 75.0,
            "total": 150.0,
            "added": "2017-08-09T09:45:15Z+03:00",
            "avail": true
        },
        {
            "id": "XXYYWW",
            "name": "Килька в томатном соусе 200г",
            "qty": 1,
            "price": 60.0,
            "total": 60.0,
            "added": "2017-08-09T09:45:15Z+03:00",
            "avail": false
        },
        {
            "id": "XXYYWW",
            "name": "Помидор красивый",
            "qty": 1,
            "price": 60.0,
            "total": 30.0,
            "weight": 0.500,
            "added": "2017-08-09T09:45:15Z+03:00",
            "avail": false
        }
    ],
    "price": {
        "items": 210,
        "delivery": 200,
        "discount": 10,
        "total": 400
    }
}

### Set Address [POST,/cart/{shopId}/delivery]
    + Attributes
        + shopId (required, string)
    + Parameters
        + shopId (required, string)
    + Request (Application/json)
        + Parameters
            shopId: "ololol"
        + Body
            {
                "address": "Южнобутовская ул. вл66",
                "entrance": "",
                "floor": "",
                "apartment": "келья дьякона Данунахова",
                "doorPhone": "1488",
                "recipientFirstName": "Иннокентий",
                "recipientLastName": "Данунахов",
                "recipientPhone": "55503523355",
                "latitude": 37.526525,
                "longitude": 55.535164,
                "note": "не кричите громко"
            }
    + Response 204 (Application/json)

### Add Item [POST,/cart/{shopId}/items]
    + Attributes
        + shopId (required, string)
    + Parameters
        + shopId (required, string)
    + Request (Application/json)
        + Parameters
            shopId: "ololol"
        + Body
            {
                "itemId": "XXYYZZ",
                "qty": 2,
                "weight": 0.4
            }
    + Response 204 (Application/json)

### Clear Cart For Shop [DELETE,/cart/{shopId}]
    + Attributes
        + shopId (required, string)
    + Parameters
        + shopId (required, string)
    + Request (Application/json)
        + Parameters
            shopId: "ololol"
    + Response 204 (Application/json)

### Modify Item [PUT,/cart/{shopId}/items/{itemId}]
    + Attributes
        + shopId (required, string)
        + itemId (required, string)
    + Parameters
        + shopId (required, string)
        + itemId (required, string)

    + Request (Application/json)
        + Parameters
            shopId: "ololol"
            itemId: "ololol"
        + Body
            {
                "qty": 2,
                "weight": 0.2
            }
    + Response 200 (Application/json)
        + Body
            {
  "item": {
    "qty": 1,
    "price": 300,
    "total": 300,
    "weight": 0.2
  },
  "cart": {
    "items": 210,
    "delivery": 200,
    "discount": 10,
    "total": 400
  }
}

### Remove Item [DELETE, /cart/{shopId}/items/{itemId}]
+ Attributes
        + shopId (required, string)
        + itemId (required, string)
    + Parameters
        + shopId (required, string)
        + itemId (required, string)

    + Request (Application/json)
        + Parameters
            shopId: "ololol"
            itemId: "ololol"
    + Response 200 (Application/json)
        + Body
            {
  "items": 210,
  "delivery": 200,
  "discount": 10,
  "total": 400
}
