
FORMAT: 1A
HOST: lama.apiary.io

# Users

Api for users

# Group Users

## CurrentUserResources [/user]

### GetUser [GET, /user]

    + Attributes
        + id (required, string)
        + firstName (required, string)
        + lastName (required, string)
        + email (required, string)
        + phone (required, string)

    + Request (application/json)
        + Headers
            Auth-token: string

    + Response 200 (application/json)

        + Body
            {
                "id": "XXYYZZ",
                "firstName": "FirstName",
                "lastName": "LastName",
                "email": "email@user.com",
                "phone": "79992223344"
            }

    + Request (application/json)
    + Response 401 (application/json)